name: Build Project

on:
  pull_request:
    branches: ['staging']

  workflow_dispatch:

jobs:
  tasks:
    runs-on: [ubuntu-20.04]
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
      - name: Build project and run tests
      - uses: nicledomaS/cmake_build_action@v1.4
        with:
          run_tests: ON
          unit_test_build: -DBUILD_TESTS=ON
