name: Build Project

on:
  push:
    branches: [staging]
  pull_request:
    branches: [staging]

  workflow_dispatch:

jobs:
  tasks:
    runs-on: [ubuntu-20.04]
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
      - uses: lukka/run-cmake@v3.4
      - name: Build project
        run: |
          make clean
          make build-test
      - name: Run tests
        run: |
          make test
          
